

services:
  servidor_mysql:
    hostname: servidor_mysql
    container_name: servidor_mysql
    image: mysql
    command: mysqld -- character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    deploy:
      resources:
        limits:
          cpus: "0.95"
          memory: 4G
    restart: always
    environment:
      environment:
        MYSQL_ROOT_PASSWORD:root
        MYSQL_USER:user2
        MYSQL_PASSWORD:senha
        TZ:America/Sao_Paulo
