version: "3.3"

services:
  servidor_mysql:
    hostname: servidor_mysql
    container_name: servidor_mysql
    image: mysql
    command: mysqld -- character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    deploy:
      resources:
        limits:
          cpus: "0.95"
          memory: 4G
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - TZ=America/Sao_Paulo